/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts --include-runtime=false` (hash: 414f864099a633153ed0e30087caa99d)
declare namespace Cloudflare {
  interface Env {
    SITEMAP_KV: KVNamespace
    NEXT_INC_CACHE_R2_BUCKET: R2Bucket
    IMAGES: ImagesBinding
    ASSETS: Fetcher
    NEXTJS_ENV: string
    WORKER_SELF_REFERENCE: Fetcher /* blog-cuong-day */
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'NEXTJS_ENV'>
  > {}
}

// Cloudflare Workers types (can't use @cloudflare/workers-types globally — conflicts with DOM types)
interface CacheStorage {
  readonly default: Cache
}

interface KVNamespace {
  get(key: string, type?: string): Promise<string | null>
  get(key: string, type: 'json'): Promise<any>
  put(
    key: string,
    value: string,
    options?: { expirationTtl?: number }
  ): Promise<void>
  delete(key: string): Promise<void>
}
