allowBuilds:
  canvas: true
  core-js: true
  protobufjs: true
  sharp: true

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@fisch0920/config'
  - lqip-modern
  - random
  - react-notion-x
  - notion-client
  - notion-types
  - notion-utils

onlyBuiltDependencies:
  - canvas
  - sharp
  - simple-git-hooks

packageManagerStrict: false
