import ExpiryMap from 'expiry-map'
import ky from 'ky'
import lqip from 'lqip-modern'
import {
  type ExtendedRecordMap,
  type PreviewImage,
  type PreviewImageMap
} from 'notion-types'
import { getPageImageUrls, normalizeUrl } from 'notion-utils'
import pMap from 'p-map'
import pMemoize from 'p-memoize'

import { defaultPageCover, defaultPageIcon } from './config'
import { dbGet, dbSet } from './db'
import persistedPreviewImagesJson from './generated/preview-images.json'
import { mapImageUrl } from './map-image-url'
import { NOTION_USER_AGENT } from './notion-api'
import { getErrorMessage } from './utils'

// Committed, prebuild-generated LQIP cache (keyed by normalizeUrl). Read first
// so builds don't re-fetch + re-process every image when Redis is disabled.
// Regenerated by notion-index.config.ts during `pnpm notion:index`.
const persistedPreviewImages = persistedPreviewImagesJson as Record<
  string,
  PreviewImage
>

export async function getPreviewImageMap(
  recordMap: ExtendedRecordMap
): Promise<PreviewImageMap> {
  const urls: string[] = getPageImageUrls(recordMap, {
    mapImageUrl
  })
    .concat([defaultPageIcon, defaultPageCover].filter(Boolean))
    .filter(Boolean)

  const previewImagesMap = Object.fromEntries(
    await pMap(
      urls,
      async (url) => {
        const cacheKey = normalizeUrl(url)
        return [cacheKey, await getPreviewImage(url, { cacheKey })]
      },
      {
        concurrency: 8
      }
    )
  )

  return previewImagesMap
}

async function createPreviewImage(
  url: string,
  { cacheKey }: { cacheKey: string }
): Promise<PreviewImage | null> {
  try {
    // Serve from the committed prebuild cache before touching db/network.
    const persisted = persistedPreviewImages[cacheKey]
    if (persisted) {
      return persisted
    }

    const cached = await dbGet<PreviewImage>(cacheKey)
    if (cached.ok && cached.value) {
      return cached.value
    }

    const body = await ky(url, {
      headers: { 'User-Agent': NOTION_USER_AGENT }
    }).arrayBuffer()
    const result = await lqip(body)

    const previewImage = {
      originalWidth: result.metadata.originalWidth,
      originalHeight: result.metadata.originalHeight,
      dataURIBase64: result.metadata.dataURIBase64
    }

    // Only write back when the read succeeded; a read error means we can't tell
    // whether a good value already exists, so don't risk clobbering it.
    if (cached.ok) {
      await dbSet(cacheKey, previewImage)
    }

    return previewImage
  } catch (err: unknown) {
    console.warn('failed to create preview image', url, getErrorMessage(err))
    return null
  }
}

// Mirrors the caching strategy in ./notion.ts: pMemoize dedupes concurrent
// calls for the same image, ExpiryMap bounds the cache so a long-lived server
// process doesn't accumulate every image URL it has ever seen, and
// `shouldCache` keeps failures out of the cache — otherwise one transient
// fetch error would permanently strip an image's LQIP placeholder for the
// life of the process.
const PREVIEW_IMAGE_CACHE_TTL_MS = 25 * 60 * 1000

export const getPreviewImage = pMemoize(createPreviewImage, {
  cacheKey: ([, { cacheKey }]) => cacheKey,
  cache: new ExpiryMap<string, PreviewImage | null>(PREVIEW_IMAGE_CACHE_TTL_MS),
  shouldCache: (result) => result !== null
})

/**
 * Build a merged, null-free preview-image map across many record maps.
 * Used at prebuild time to generate the committed lib/generated/preview-images.json.
 */
export async function buildPreviewImageMap(
  recordMaps: ExtendedRecordMap[]
): Promise<Record<string, PreviewImage>> {
  const merged: Record<string, PreviewImage> = {}

  for (const recordMap of recordMaps) {
    const map = await getPreviewImageMap(recordMap)
    for (const [key, value] of Object.entries(map)) {
      if (value) {
        merged[key] = value
      }
    }
  }

  return merged
}
