import ky from 'ky'
import lqip from 'lqip-modern'
import {
  type ExtendedRecordMap,
  type PreviewImage,
  type PreviewImageMap
} from 'notion-types'
import { getPageImageUrls, normalizeUrl } from 'notion-utils'
import pMap from 'p-map'
import pMemoize from 'p-memoize'

import { defaultPageCover, defaultPageIcon } from './config'
import { db } from './db'
import persistedPreviewImagesJson from './generated/preview-images.json'
import { mapImageUrl } from './map-image-url'
import { getErrorMessage } from './utils'

// Committed, prebuild-generated LQIP cache (keyed by normalizeUrl). Read first
// so builds don't re-fetch + re-process every image when Redis is disabled.
// Regenerated by notion-index.config.ts during `pnpm notion:index`.
const persistedPreviewImages = persistedPreviewImagesJson as Record<
  string,
  PreviewImage
>

export async function getPreviewImageMap(
  recordMap: ExtendedRecordMap
): Promise<PreviewImageMap> {
  const urls: string[] = getPageImageUrls(recordMap, {
    mapImageUrl
  })
    .concat([defaultPageIcon, defaultPageCover].filter(Boolean))
    .filter(Boolean)

  const previewImagesMap = Object.fromEntries(
    await pMap(
      urls,
      async (url) => {
        const cacheKey = normalizeUrl(url)
        return [cacheKey, await getPreviewImage(url, { cacheKey })]
      },
      {
        concurrency: 8
      }
    )
  )

  return previewImagesMap
}

async function createPreviewImage(
  url: string,
  { cacheKey }: { cacheKey: string }
): Promise<PreviewImage | null> {
  try {
    // Serve from the committed prebuild cache before touching db/network.
    const persisted = persistedPreviewImages[cacheKey]
    if (persisted) {
      return persisted
    }

    try {
      const cachedPreviewImage = await db.get(cacheKey)
      if (cachedPreviewImage) {
        return cachedPreviewImage
      }
    } catch (err: unknown) {
      // ignore redis errors
      console.warn(`redis error get "${cacheKey}"`, getErrorMessage(err))
    }

    const body = await ky(url).arrayBuffer()
    const result = await lqip(body)

    const previewImage = {
      originalWidth: result.metadata.originalWidth,
      originalHeight: result.metadata.originalHeight,
      dataURIBase64: result.metadata.dataURIBase64
    }

    try {
      await db.set(cacheKey, previewImage)
    } catch (err: unknown) {
      // ignore redis errors
      console.warn(`redis error set "${cacheKey}"`, getErrorMessage(err))
    }

    return previewImage
  } catch (err: unknown) {
    console.warn('failed to create preview image', url, getErrorMessage(err))
    return null
  }
}

export const getPreviewImage = pMemoize(createPreviewImage)

/**
 * Build a merged, null-free preview-image map across many record maps.
 * Used at prebuild time to generate the committed lib/generated/preview-images.json.
 */
export async function buildPreviewImageMap(
  recordMaps: ExtendedRecordMap[]
): Promise<Record<string, PreviewImage>> {
  const merged: Record<string, PreviewImage> = {}

  for (const recordMap of recordMaps) {
    const map = await getPreviewImageMap(recordMap)
    for (const [key, value] of Object.entries(map)) {
      if (value) {
        merged[key] = value
      }
    }
  }

  return merged
}
